<?php $tree = $block->getTree();
if($tree):
?>
<div class="baniwal-sidebar mpcss">
    <div class="row">
        <div class="block-title col-xs-12 sidebar-categories">
            <p class="block-baniwal-sidebar-heading" role="heading" aria-label="2"><?php echo __('Categories') ?></p>
        </div>
        <div class="col-xs-12">
                <?php echo $block->getCategoryTreeHtml($tree) ?>
        </div>
    </div>
</div>
<script type="text/javascript">
    require(['Baniwal_Blog/js/categorytree'], function () {});
</script>
<?php endif; ?>