<?php
$helper = $this->helper('Baniwal\Blog\Helper\Data');
if ($helper->isEnabled() && $helper->getBlogConfig('general/toplinks')): ?>
    <li class="nav-item level0 nav-5 level-top classic">
        <a href="<?php echo $helper->getBlogUrl('') ?>" class="level-top">
            <span><?php echo $helper->getBlogConfig('general/name') ?: __('Blog') ?></span>
        </a>
    </li>
<?php endif; ?>