<?php
$dateArrayCount = $block->getDateArrayCount();
$dateArrayUnique = $block->getDateArrayUnique();
$dateLabel = $block->getDateLabel();

if ($block->isEnable() && $dateArrayUnique): ?>
<div class="baniwal-sidebar mpcss">
	<div class="row">
		<div class="block-title col-xs-12 sidebar-archives">
            <p class="block-baniwal-sidebar-heading" role="heading" aria-level="2"><?php echo __('Monthly Archive') ?></p>
		</div>
        <div class="block-content">
            <ul class="menu-archives">
             <?php for ($i=0; $i<$block->getDateCount(); $i++): ?>
                <li class="archive-item" >
                    <a class="list-archives" href="<?php echo $block->getMonthlyUrl(date("Y-m",$this->dateTime->timestamp($dateArrayUnique[$i]))) ?>">
                         <i class="fa fa-calendar" aria-hidden="true"></i>&nbsp;&nbsp;
                        <?php echo $dateLabel[$i].'   ('.$dateArrayCount[$i].')'; ?>
                    </a>
                </li>
              <?php endfor; ?>
            </ul>
        </div>
    </div>
</div>
<?php endif; ?>
