<?php $tags = $block->getTagList();
if ($tags && $tags->getSize()): ?>
<div class="baniwal-sidebar baniwalcss">
	<div class="row">
		<div class="block-title col-xs-12 sidebar-tags">
            <p class="block-baniwal-sidebar-heading" role="heading" aria-level="2"><?php echo __('Tags') ?></p>
		</div>
		<div class="block-content">
        <?php foreach ($tags as $tag): ?>
            <a class="label label-default tags-list"
               style="font-size:<?php echo $block->getTagSize($tag) . 'px'; ?>"
               href="<?php echo $block->getTagUrl($tag) ?>">
                <?php echo $tag->getName(); ?>
            </a>
        <?php endforeach; ?>
		</div>
    </div>
</div>
<?php endif; ?>
