<?php $posts = $block->getCollection(); ?>
<div class="blog-widget-title"><a ></a></div>
<div class="post-list-container baniwalcss" id="baniwalblog-list-container">
    <div class="widget-title">
        <a href="<?php echo $block->getBlogUrl(''); ?>"><?php echo $block->getTitle(); ?></a>
    </div>
    <div class="row">
        <?php foreach ($posts as $post) : ?>
            <div class="post-list-item col-sm-4 col-xs-4">
                <div class="post-item-wraper">
                    <?php if ($post->getImage()) : ?>
                        <div class="post-image">
                            <a href="<?php echo $post->getUrl() ?>">
                                <img class="img-responsive" style="height: 220px"
                                     src="<?php echo $block->resizeImage($post->getImage(), '400x'); ?>"
                                     alt="<?php echo $block->escapeHtml($post->getName()); ?>"/>
                            </a>
                        </div>
                    <?php endif; ?>
                    <div class="post-info-wraper">
                        <h2 class="baniwal-post-title" style="font-size: 22px">
                            <a class="post-link-title" title="<?php echo $post->getName(); ?>" href="<?php echo $post->getUrl() ?>">
                                <?php echo $post->getName();?>
                            </a>
                        </h2>
                        <div class="baniwal-post-info">
                            <?php echo $block->getPostInfo($post) ?>
                        </div>
                        <div class="post-short-description">
                            <p><?php echo $post->getShortDescription(); ?></p>
                        </div>
                        <div class="baniwal-clearfix"></div>
                        <div class="baniwal-post-meta-info baniwal-alignright">
                            <div class="actions">
                                <a class="baniwal-read-more" href="<?php echo $post->getUrl(); ?>" title="<?php echo __('Read More'); ?>"><?php echo __('Read more'); ?></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>
